apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-a.fullname" . }}
  labels:
    app: {{ include "service-a.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "service-a.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "service-a.name" . }}
    spec:
      containers:
        - name: service-a
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/healthdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"