apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-a.fullname" . }}-db
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
