replicaCount: 1

image:
  repository: health-support-app/service-a
  pullPolicy: IfNotPresent
  tag: "local"

service:
  type: ClusterIP
  port: 8080

database:
  url: "jdbc:postgresql://postgres:5432/healthdb"
  username: "postgres"
  password: "postgres"

postgres:
  image: "postgres:15-alpine"
  database: "healthdb"
  storage: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

tolerations: []